params:
  seed: ${...seed}
  framework: PPO

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd  # ndp

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 256, 128, 64]
      activation: tanh
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  dmp:  # If active applies dmp in between policy and env
    active: False
    type: discrete
    rbfs:
      numRBFs: 20
      kernel: "gaussian"
    gains:  # Set to beta = alpha_z / 4 and alpha_x = alpha_z / 3
      fixed: True
      scale: 1  # if fixed initialized at 1 * scale else scales incoming input
    tau:
      fixed: True  # TODO: Implement variable case
      scale: 1  # if fixed initialized at 1 * scale
    weight_scale: 1
    dt: ${....task.sim.dt}
    controlFrequencyInv: ${....task.env.controlFrequencyInv}

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:FoosballSelfPlay,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    clip_actions: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-3
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.008
    score_to_win: 10000000
    max_epochs: ${resolve_default:100000,${....max_iterations}}
    save_best_after: 100
    save_frequency: 500
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 64  # 64  # 16
    minibatch_size: 32768  # 65536  # 16384
    mini_epochs: 8
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001

    self_play_config:
      update_score: 0.2
      games_to_check: 100
      env_update_num: 1
      check_scores: True

    env_config:
      name: foosball_self_play_v0
      self_play: True
      agents: 2
      config_path: cfg/train/FoosballSelfPlayPPO.yaml

