params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd  # continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: tanh
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None
    dmp: # Only for ndp models
      numRBFs: 20
      steps: 10
      kernel: "gaussian"
      target_crossing: True
      optimize_hyperparameters: True
      hyperparameter_scale: 1
      weight_scale: 1
      dt: ${.....task.sim.dt}
      controlFrequencyInv: ${.....task.env.controlFrequencyInv}

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:FoosballGoalShot,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    clip_actions: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-3
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.008
    score_to_win: 10000000
    max_epochs: ${resolve_default:1500,${....max_iterations}}
    save_best_after: 100
    save_frequency: 200
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 16384  # 32768  # 16384  # 8192
    mini_epochs: 8
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
